name: Update blocklist

on:
  push:
    paths:
      - 'domains.txt'
  workflow_dispatch:

jobs:
  process:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run process
      run: ./process.sh

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git commit -m "Update blocklist"; then
          git push
        fi